//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : KalkulatorPodatkowy.cpp
//  @ Date : 14.04.2026
//  @ Author : 
//
//


#include "KalkulatorPodatkowy.h"

using namespace std;

KalkulatorPodatkowy::KalkulatorPodatkowy(double vat, string waluta) {
    stawkaVAT = vat;
    symbolWaluty = waluta;
}

double KalkulatorPodatkowy::obliczBrutto(double kwotaNetto) {
    return kwotaNetto + (kwotaNetto * stawkaVAT);
}

string KalkulatorPodatkowy::pobierzWalute() {
    return symbolWaluty;
}
