//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : KalkulatorPodatkowy.h
//  @ Date : 14.04.2026
//  @ Author : 
//
//


#if !defined(_KALKULATORPODATKOWY_H)
#define _KALKULATORPODATKOWY_H

#include <string>

class KalkulatorPodatkowy {
public:
    KalkulatorPodatkowy(double vat, std::string waluta); 
    double obliczBrutto(double kwotaNetto);
    std::string pobierzWalute();
private:
    double stawkaVAT;
    std::string symbolWaluty;
};

#endif //_KALKULATORPODATKOWY_H