//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : KoszykZakupowy.cpp
//  @ Date : 14.04.2026
//  @ Author : 
//
//


#include <iostream>
#include "KoszykZakupowy.h"

using namespace std;

// Poprawiona nazwa w implementacji
KoszykZakupowy::KoszykZakupowy(string id, string klient) {
    idKoszyka = id;
    wlasciciel = klient;
}

void KoszykZakupowy::dodajProdukt(string nazwa, double cena, int ilosc) {
    pozycje.emplace_back(nazwa, cena, ilosc);
}

void KoszykZakupowy::oproznijKoszyk() {
    pozycje.clear();
    cout << "Koszyk (" << idKoszyka << ") zostal oprozniony." << endl;
}

void KoszykZakupowy::generujPodsumowanie(KalkulatorPodatkowy kalkulator) {
    cout << "\nPodsumowanie Koszyka klienta: " << wlasciciel << endl;
    double sumaCalkowita = 0.0;

    for (auto& pozycja : pozycje) {
        double wartosc = pozycja.wyliczWartoscPozycji(kalkulator);
        sumaCalkowita += wartosc;
        cout << "- " << pozycja.pobierzNazwe() << " -> " 
             << wartosc << " " << kalkulator.pobierzWalute() << endl;
    }
    cout << "RAZEM DO ZAPLATY: " << sumaCalkowita << " " << kalkulator.pobierzWalute() << "\n\n";
}
