//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : KoszykZakupowy.h
//  @ Date : 14.04.2026
//  @ Author : 
//
//


#if !defined(_KOSZYKZAKUPOWY_H)
#define _KOSZYKZAKUPOWY_H

#include <string>
#include <vector>
#include "PozycjaWKoszyku.h"
#include "KalkulatorPodatkowy.h"

class KoszykZakupowy {
public:
    KoszykZakupowy(std::string id, std::string klient);
    void dodajProdukt(std::string nazwa, double cena, int ilosc);
    void oproznijKoszyk();
    void generujPodsumowanie(KalkulatorPodatkowy kalkulator);
private:
    std::string idKoszyka;
    std::string wlasciciel;
    std::vector<PozycjaWKoszyku> pozycje;
};
#endif //_KOSZYKZAKUPOWY_H