//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : PozycjaWKoszyku.h
//  @ Date : 14.04.2026
//  @ Author : 
//
//


#if !defined(_POZYCJAWKOSZYKU_H)
#define _POZYCJAWKOSZYKU_H

#include <string>
#include "KalkulatorPodatkowy.h"

class PozycjaWKoszyku {
public:
    PozycjaWKoszyku(std::string nazwa, double cena, int ilosc);
    void zmienIlosc(int nowaIlosc);
    double wyliczWartoscPozycji(KalkulatorPodatkowy kalkulator);
    std::string pobierzNazwe();

private:
    std::string nazwaTowaru;
    double cenaJednostkowaNetto;
    int iloscSztuk;
};

#endif //_POZYCJAWKOSZYKU_H
