//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : PozycjaWKoszyku.cpp
//  @ Date : 14.04.2026
//  @ Author : 
//
//


#include "PozycjaWKoszyku.h"

using namespace std;

PozycjaWKoszyku::PozycjaWKoszyku(string nazwa, double cena, int ilosc) {
    nazwaTowaru = nazwa;
    cenaJednostkowaNetto = cena;
    iloscSztuk = ilosc;
}

void PozycjaWKoszyku::zmienIlosc(int nowaIlosc) {
    if (nowaIlosc > 0) {
        iloscSztuk = nowaIlosc;
    }
}

double PozycjaWKoszyku::wyliczWartoscPozycji(KalkulatorPodatkowy kalkulator) {
    double wartoscNetto = cenaJednostkowaNetto * iloscSztuk;
    return kalkulator.obliczBrutto(wartoscNetto);
}

string PozycjaWKoszyku::pobierzNazwe() {
    return nazwaTowaru;
}