//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Schronisko.cpp
//  @ Date : 24.03.2026
//  @ Author : 
//
//


#include "Schronisko.h"
#include "Pies.h"
#include <iostream>

Schronisko::Schronisko(int ilosc_psow, int miejsca) {
    this->ilosc_psow = ilosc_psow;
    this->miejsca = miejsca;
}

int Schronisko::get_ilosc_psow() {
    return psy.size();
}

int Schronisko::get_miejsca() {
    return miejsca;
}

void Schronisko::set_ilosc_psow(int ilosc_psow) {
    this->ilosc_psow = ilosc_psow;
}

void Schronisko::set_miejsca(int miejsca) {
    this->miejsca = miejsca;
}

void Schronisko::przyjmij_psa(Pies p) {
    if(psy.size() < miejsca){
        psy.push_back(p);
        ilosc_psow = psy.size();
        cout<<"Przyjeto psa: "<<p.get_imie() <<". Stan schroniska: "<<ilosc_psow<<"/"<<miejsca<<endl; 
    }else{
        cout<<"Brak miejsc!"<<endl;
    }
}

void Schronisko::wydaj_psa(int id) {
    bool found = false;
    for(int i = 0; i<psy.size();i++){
        if(psy[i].get_id()==id){
            cout<<"Wydano psa: "<<psy[i].get_imie<<"(ID = "<<id<<")"<<endl;
            psy.erase(psy.begin()+i);
            found = true;
            break;
        }
    }
    if(found){
        ilosc_psow = psy.size();
    }
    else{
        cout<<"Nie znaleziono psa o ID = "<<id<<endl;
    }
}

