//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Schronisko.h
//  @ Date : 24.03.2026
//  @ Author : 
//
//


#if !defined(_SCHRONISKO_H)
#define _SCHRONISKO_H

#include "Pies.h"
#include <vector>
#include <iostream>

using namespace std;


class Schronisko {
public:
	Schronisko(int ilosc_psow, int miejsca);
	int get_ilosc_psow();
	int get_miejsca();
	void set_ilosc_psow(int ilosc_psow);
	void set_miejsca(int miejsca);
	void przyjmij_psa(Pies p);
	void wydaj_psa(int id);
private:
	int ilosc_psow;
	int miejsca;
	vector<Pies> psy;
};

#endif  //_SCHRONISKO_H
