//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : CzujnikTemperatury.cpp
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#include "CzujnikTemperatury.h"
#include <algorithm>

void CzujnikTemperatury::attach(IAlarm* o) { 
    observers.push_back(o); 
}

void CzujnikTemperatury::detach(IAlarm* o) { 
    observers.remove(o); 
}

void CzujnikTemperatury::notify(float temp) {
    for (auto o : observers) {
        o->update(temp);
    }
}

void CzujnikTemperatury::setTemperatura(float t) {
    temperatura = t;
    if (temperatura > 60.0f) notify(temperatura);
}

float CzujnikTemperatury::GetState() const { return temperatura; }
