//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : DyskTwardy.cpp
//  @ Date : 14.04.2026
//  @ Author : 
//
//


#include "DyskTwardy.h"
#include <iostream>

DyskTwardy::DyskTwardy(std::string producent) {
    this->producent = producent;
    std::cout << "Utworzono dysk: " << producent << "\n";
}

DyskTwardy::~DyskTwardy() {
    std::cout << "Zniszczono dysk: " << producent << "\n";
}

void DyskTwardy::formatujPartycje(std::string litera, int rozmiar) {
    partycje.push_back(Partycja(litera, rozmiar));
}

void DyskTwardy::wypiszPartycje() {
    std::cout << "Dysk: " << producent << "\n";
    for (auto& p : partycje) {
        std::cout << "  - " << p.getInfo() << "\n";
    }
}

