//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : DyskTwardy.h
//  @ Date : 14.04.2026
//  @ Author : 
//
//


#if !defined(_DYSKTWARDY_H)
#define _DYSKTWARDY_H

#include <string>
#include <vector>
#include "Partycja.h"

class DyskTwardy {
public:
    DyskTwardy(std::string producent);
    ~DyskTwardy();
    void formatujPartycje(std::string litera, int rozmiar);
    void wypiszPartycje();
private:
    std::string producent;
    std::vector<Partycja> partycje;
};

#endif  //_DYSKTWARDY_H
