//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Komputer.h
//  @ Date : 14.04.2026
//  @ Author : 
//
//


#if !defined(_KOMPUTER_H)
#define _KOMPUTER_H

#include <string>
#include <vector>
#include "DyskTwardy.h"

class Komputer {
public:
    Komputer(std::string model);
    ~Komputer();
    void podlaczDysk(DyskTwardy* dysk);
    void wypiszStatus();
private:
    std::string model;
    std::vector<DyskTwardy*> dyski;
};

#endif  //_KOMPUTER_H
