//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Komputer.cpp
//  @ Date : 14.04.2026
//  @ Author : 
//
//


#include "Komputer.h"
#include <iostream>

Komputer::Komputer(std::string model) {
    this->model = model;
    std::cout << "Zlozono komputer: " << model << "\n";
}

Komputer::~Komputer() {
    std::cout << "Zezlomowano komputer: " << model << "\n";
}

void Komputer::podlaczDysk(DyskTwardy* dysk) {
    dyski.push_back(dysk);
}

void Komputer::wypiszStatus() {
    std::cout << "Komputer: " << model << "\n";
    for (auto* d : dyski) {
        d->wypiszPartycje();
    }
}
