//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Partycja.cpp
//  @ Date : 14.04.2026
//  @ Author : 
//
//


#include "Partycja.h"
#include <iostream>

Partycja::Partycja(std::string litera, int rozmiar) {
    this->litera = litera;
    this->rozmiarGB = rozmiar;
    std::cout << "Utworzono partycje: " << litera << "\n";
}

Partycja::~Partycja() {
    std::cout << "Usunieto partycje: " << litera << "\n";
}

std::string Partycja::getInfo() {
    return "Partycja " + litera + " [" + std::to_string(rozmiarGB) + " GB]";
}
