//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Partycja.h
//  @ Date : 14.04.2026
//  @ Author : 
//
//


#if !defined(_PARTYCJA_H)
#define _PARTYCJA_H

#include <string>

class Partycja {
public:
    Partycja(std::string litera, int rozmiar);
    ~Partycja();
    std::string getInfo();
private:
    std::string litera;
    int rozmiarGB;
};

#endif  //_PARTYCJA_H
