//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.cpp
//  @ Date : 10.03.2026
//  @ Author : 
//
//


#include "Pies.h"

Pies::Pies(string imie, string rasa, int wiek, float waga) : Ssak(waga, wiek) {
    this->imie = imie;
    this->rasa = rasa;
}

string Pies::szczekaj() {
    return "hau";
}

string Pies::daj_lape() {
    return "daje lape";
}

int Pies::get_wiek() {
    return this->wiek;
}

float Pies::get_waga() {
    return this->waga;
}

string Pies::get_imie() {
    return this->imie;
}

string Pies::get_rasa() {
    return this->rasa;
}

void Pies::set_wiek(int wiek) {
    this->wiek = wiek;
}

void Pies::set_waga(float waga) {
    this->waga = waga;
}

void Pies::set_imie(string imie) {
    this->imie = imie;
}

void Pies::set_rasa(string rasa) {
    this->rasa = rasa;
}

