//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.h
//  @ Date : 10.03.2026
//  @ Author : 
//
//


#if !defined(_PIES_H)
#define _PIES_H

#include "Ssak.h"
#include <string>
using namespace std;

class Pies : public Ssak {
public:
	Pies(string imie, string rasa, int wiek, float waga);
	string szczekaj();
	string daj_lape();
	int get_wiek();
	float get_waga();
	string get_imie();
	string get_rasa();
	void set_wiek(int wiek);
    void set_waga(float waga);
    void set_imie(string imie);
    void set_rasa(string rasa);
private:
	string imie;
	string rasa;
};

#endif  //_PIES_H
