//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.h
//  @ Date : 10.03.2026
//  @ Author : 
//
//


#if !defined(_SSAK_H)
#define _SSAK_H


class Ssak {
public:
	Ssak(float waga, int wiek);
protected:
	int wiek;
	float waga;
};

#endif  //_SSAK_H
