//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.cpp
//  @ Date : 10.03.2026
//  @ Author : 
//
//


#include "Ssak.h"

Ssak::Ssak(float waga, int wiek) {
    this->waga = waga;
    this->wiek = wiek;
}

