//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.cpp
//  @ Date : 24.03.2026
//  @ Author : 
//
//


#include "Pies.h"
#include <string>

using namespace std;

Pies::Pies(string imie, string rasa, int wiek, float waga, int id) : Ssak(waga, wiek) {
    this->imie = imie;
    this->rasa = rasa;
    this->id = id;
    this->set_wiek(wiek); 
    this->set_waga(waga);
}

string Pies::szczekaj() {
    return "Hau hau!";
}

string Pies::daj_lape() {
    return "*Podaje lape*";
}

string Pies::get_imie() {
    return imie;
}

string Pies::get_rasa() {
    return rasa;
}

void Pies::set_imie(string imie) {
    this->imie = imie;
}

void Pies::set_rasa(string rasa) {
    this->rasa = rasa;
}

void Pies::set_id(int id) {
    this->id = id;
}

int Pies::get_id() {
    return id;
}

