//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Pies.h
//  @ Date : 24.03.2026
//  @ Author : 
//
//


#if !defined(_PIES_H)
#define _PIES_H

#include "Ssak.h"
#include <string>

using namespace std;

class Pies : public Ssak {
public:
	Pies(string imie, string rasa, int wiek, float waga, int id);
	string szczekaj();
	string daj_lape();
	string get_imie();
	string get_rasa();
	void set_imie(string imie);
	void set_rasa(string rasa);
	void set_id(int id);
	int get_id();
private:
	string imie;
	string rasa;
	int id;
};

#endif  //_PIES_H
