//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Schronisko.cpp
//  @ Date : 24.03.2026
//  @ Author : 
//
//


#include "Schronisko.h"
#include "Pies.h"
#include <iostream>

using namespace std;

Schronisko::Schronisko(int ilosc_psow, int miejsca) {
    this->ilosc_psow = ilosc_psow;
    this->miejsca = miejsca;
}

int Schronisko::get_ilosc_psow() {
    return ilosc_psow;
}

int Schronisko::get_miejsca() {
    return miejsca;
}

void Schronisko::set_ilosc_psow(int ilosc_psow) {
    this->ilosc_psow = ilosc_psow;
}

void Schronisko::set_miejsca(int miesjca) {
    this->miejsca = miejsca;
}

void Schronisko::przyjmij_psa(Pies p) {
    if (ilosc_psow < miejsca) {
        ilosc_psow++;
        cout << "Przyjeto psa " << p.get_imie() << ". Obecna ilosc psow: " << ilosc_psow << "/" << miejsca << endl;
    } else {
        cout << "Brak miejsc w schronisku!" << endl;
    }
}

void Schronisko::wydaj_psa(int id) {
    if (ilosc_psow > 0) {
        ilosc_psow--;
        cout << "Wydano psa o ID " << id << ". Pozostalo psow: " << ilosc_psow << "/" << miejsca << endl;
    } else {
        cout << "Schronisko jest puste!" << endl;
    }
}

