//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.h
//  @ Date : 24.03.2026
//  @ Author : 
//
//


#if !defined(_SSAK_H)
#define _SSAK_H

#include <iostream>

using namespace std;

class Ssak {
public:
	Ssak(float waga, int wiek);
	void set_wiek(int wiek);
	void set_waga(float waga);
	int get_wiek();
	float get_waga();
private:
	int wiek;
	float waga;
};

#endif  //_SSAK_H
