//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Ssak.cpp
//  @ Date : 24.03.2026
//  @ Author : 
//
//


#include "Ssak.h"

Ssak::Ssak(float waga, int wiek) {
    this->waga = waga;
    this->wiek = wiek;
}

void Ssak::set_wiek(int wiek) {
    this->wiek = wiek;
}

void Ssak::set_waga(float waga) {
    this->waga = waga;
}

int Ssak::get_wiek() {
    return wiek;
}

float Ssak::get_waga() {
    return waga;
}

