//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AutoOsobowe.cpp
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#include "AutoOsobowe.h"



