//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : AutoOsobowe.h
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#if !defined(_AUTOOSOBOWE_H)
#define _AUTOOSOBOWE_H


class AutoOsobowe {
public:
    virtual ~AutoOsobowe() {}
    virtual void wyswietlInfo() = 0;
    virtual void skonfiguruj(int param) = 0;
};

#endif  //_AUTOOSOBOWE_H
