//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Client.cpp
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#include "Client.h"
#include "IFabrykaPojazdow.h"
#include "AutoOsobowe.h"
#include "SamochodDostawczy.h"

void Client::konfigurujFlote(IFabrykaPojazdow* f) {
    AutoOsobowe* autoOsobowe = f->stworzAutoOsobowe();
    SamochodDostawczy* dostawczak = f->stworzSamochodDostawczy();
    autoOsobowe->skonfiguruj(150); 
    dostawczak->skonfiguruj(1000);

    autoOsobowe->wyswietlInfo();
    dostawczak->wyswietlInfo();

    delete autoOsobowe;
    delete dostawczak;
}

