//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : Client.h
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#if !defined(_CLIENT_H)
#define _CLIENT_H

class IFabrykaPojazdow;

class Client {
public:
	void konfigurujFlote(IFabrykaPojazdow* f);
};

#endif  //_CLIENT_H
