//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ElektryczneAutoOsobowe.cpp
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#include "ElektryczneAutoOsobowe.h"
#include <iostream>

using namespace std;

void ElektryczneAutoOsobowe::skonfiguruj(int batKWh) { this->pojemnoscBaterii = batKWh; }
void ElektryczneAutoOsobowe::wyswietlInfo() {
    cout << " -> Auto Osobowe (Elektryczne), Bateria: " << pojemnoscBaterii << " kWh." << endl;
}
