//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ElektrycznySamochodDostawczy.cpp
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#include "ElektrycznySamochodDostawczy.h"
#include <iostream>

using namespace std;

void ElektrycznySamochodDostawczy::skonfiguruj(int ladownoscKG) {
    this->ladownosc = ladownoscKG;
}
void ElektrycznySamochodDostawczy::wyswietlInfo() {
    cout << " -> Samochod Dostawczy (Elektryczny), Ladownosc: " << ladownosc << " kg." << endl;
}

