//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ElektryczneAutoOsobowe.h
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#if !defined(_ELEKTRYCZNEAUTOOSOBOWE_H)
#define _ELEKTRYCZNEAUTOOSOBOWE_H

#include "AutoOsobowe.h"

class ElektryczneAutoOsobowe : public AutoOsobowe {
private:
    int pojemnoscBaterii;
public:
	void wyswietlInfo() override;
    void skonfiguruj(int param) override;
};

#endif  //_ELEKTRYCZNEAUTOOSOBOWE_H
