//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : ElektrycznySamochodDostawczy.h
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#if !defined(_ELEKTRYCZNYSAMOCHODDOSTAWCZY_H)
#define _ELEKTRYCZNYSAMOCHODDOSTAWCZY_H

#include "SamochodDostawczy.h"

class ElektrycznySamochodDostawczy : public SamochodDostawczy {
private:
    int ladownosc;
	int pojemnoscBaterii;
public:
	void wyswietlInfo() override;
	void skonfiguruj(int param) override;
};

#endif  //_ELEKTRYCZNYSAMOCHODDOSTAWCZY_H
