//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : FabrykaPojazdowElektrycznych.cpp
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#include "FabrykaPojazdowElektrycznych.h"
#include "ElektryczneAutoOsobowe.h"
#include "ElektrycznySamochodDostawczy.h"

AutoOsobowe* FabrykaPojazdowElektrycznych::stworzAutoOsobowe() {
    return new ElektryczneAutoOsobowe();
}

SamochodDostawczy* FabrykaPojazdowElektrycznych::stworzSamochodDostawczy() {
    return new ElektrycznySamochodDostawczy();
}

