//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : FabrykaPojazdowSpalinowych.cpp
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#include "FabrykaPojazdowSpalinowych.h"
#include "SpalinoweAutoOsobowe.h"
#include "SpalinowySamochodDostawczy.h"

AutoOsobowe* FabrykaPojazdowSpalinowych::stworzAutoOsobowe() {
    return new SpalinoweAutoOsobowe();
}

SamochodDostawczy* FabrykaPojazdowSpalinowych::stworzSamochodDostawczy() {
    return new SpalinowySamochodDostawczy();
}

