//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : FabrykaPojazdowSpalinowych.h
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#if !defined(_FABRYKAPOJAZDOWSPALINOWYCH_H)
#define _FABRYKAPOJAZDOWSPALINOWYCH_H

#include "IFabrykaPojazdow.h"
#include "AutoOsobowe.h"
#include "SamochodDostawczy.h"

class FabrykaPojazdowSpalinowych : public IFabrykaPojazdow {
public:
	AutoOsobowe* stworzAutoOsobowe() override;
	SamochodDostawczy* stworzSamochodDostawczy() override;
};

#endif  //_FABRYKAPOJAZDOWSPALINOWYCH_H
