//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : FabrykaPojazdowElektrycznych.h
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#if !defined(_FABRYKAPOJAZDOWELEKTRYCZNYCH_H)
#define _FABRYKAPOJAZDOWELEKTRYCZNYCH_H

#include "IFabrykaPojazdow.h"
#include "AutoOsobowe.h"
#include "SamochodDostawczy.h"

class FabrykaPojazdowElektrycznych : public IFabrykaPojazdow {
public:
	AutoOsobowe* stworzAutoOsobowe() override;
	SamochodDostawczy* stworzSamochodDostawczy() override;
};

#endif  //_FABRYKAPOJAZDOWELEKTRYCZNYCH_H