//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : IFabrykaPojazdow.h
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#if !defined(_IFABRYKAPOJAZDOW_H)
#define _IFABRYKAPOJAZDOW_H


class AutoOsobowe;
class SamochodDostawczy;

class IFabrykaPojazdow {
public:
	virtual ~IFabrykaPojazdow() {}
	virtual AutoOsobowe* stworzAutoOsobowe() = 0;
	virtual SamochodDostawczy* stworzSamochodDostawczy() = 0;
};

#endif  //_IFABRYKAPOJAZDOW_H
