//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SamochodDostawczy.cpp
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#include "SamochodDostawczy.h"



