//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SamochodDostawczy.h
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#if !defined(_SAMOCHODDOSTAWCZY_H)
#define _SAMOCHODDOSTAWCZY_H


class SamochodDostawczy {
public:
	virtual ~SamochodDostawczy() {}
	virtual void wyswietlInfo() = 0;
	virtual void skonfiguruj(int param) = 0;
};

#endif  //_SAMOCHODDOSTAWCZY_H
