//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SpalinoweAutoOsobowe.h
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#if !defined(_SPALINOWEAUTOOSOBOWE_H)
#define _SPALINOWEAUTOOSOBOWE_H

#include "AutoOsobowe.h"

class SpalinoweAutoOsobowe : public AutoOsobowe {
private:
    int moc;
public:
	void wyswietlInfo() override;
    void skonfiguruj(int param) override;
};

#endif  //_SPALINOWEAUTOOSOBOWE_H
