//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SpalinowySamochodDostawczy.h
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#if !defined(_SPALINOWYSAMOCHODDOSTAWCZY_H)
#define _SPALINOWYSAMOCHODDOSTAWCZY_H

#include "SamochodDostawczy.h"

class SpalinowySamochodDostawczy : public SamochodDostawczy {
private:
    int ladownosc;
    int moc;
public:
	void wyswietlInfo() override;
    void skonfiguruj(int param) override;
};

#endif  //_SPALINOWYSAMOCHODDOSTAWCZY_H
