//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SpalinoweAutoOsobowe.cpp
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#include "SpalinoweAutoOsobowe.h"
#include <iostream>

using namespace std;

void SpalinoweAutoOsobowe::skonfiguruj(int mocKM) { this->moc = mocKM; }
void SpalinoweAutoOsobowe::wyswietlInfo() {
    cout << " -> Auto Osobowe (Spalinowe), Moc: " << moc << " KM." << endl;
}

