//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : SpalinowySamochodDostawczy.cpp
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#include "SpalinowySamochodDostawczy.h"
#include <iostream>

using namespace std;

void SpalinowySamochodDostawczy::skonfiguruj(int param) { this->ladownosc = param; }
void SpalinowySamochodDostawczy::wyswietlInfo() {
    cout << " -> Samochod Dostawczy (Spalinowy), Ladownosc: " << ladownosc << " kg." << endl;
}

