//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TBernouli.cpp
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#include "TBernouli.h"
#include <iostream>
using namespace std;

void TBernouli::bernouli(double p, int n, int k) {
    q = 1.0 - p;
    P = (pNewton.newton(n, k) * pPower.power(p, k) * pPower.power(q, n - k));
    
    cout << "\nPrawdopodobienstwo, ze w " << n << " doswiadczeniach "
         << k << "-razy otrzymamy sukces wynosi: \n" << P << "\n\n";
}

TBernouli::TBernouli() {
    cout << "Utworzono obiekt klasy TBernouli (oraz pPower i pNewton)\n";
}

TBernouli::~TBernouli() {
    cout << "Zniszczono obiekt klasy TBernouli\n";
}

