//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TBernouli.h
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#if !defined(_TBERNOULI_H)
#define _TBERNOULI_H

#include "TPower.h"
#include "TNewton.h"

class TBernouli {
public:
	void bernouli(double p, int n, int k);
	TBernouli();
	~TBernouli();
private:
	double q;
	long double P;
	TPower pPower;
	TNewton pNewton;
	
};

#endif  //_TBERNOULI_H
