//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TFactorial.cpp
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#include "TFactorial.h"

long double TFactorial::factorial(int n) {
    if (n == 0) return 1;
    return n * factorial(n - 1);
}

