//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TNewton.cpp
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#include "TNewton.h"
#include <iostream>
using namespace std;

long double TNewton::newton(int n, int k) {
    N = n - k;
    long double NbyK = 1;
    
    if (k >= N) {
        for(int i = k + 1; i <= n; i++) NbyK *= i;
        return (NbyK / pFactorial.factorial(n - k));
    } else {
        for(int i = N + 1; i <= n; i++) NbyK *= i;
        return (NbyK / pFactorial.factorial(k));
    }
}

TNewton::TNewton() {
    cout << "Utworzono obiekt klasy TNewton (i jego TFactorial)\n";
}

TNewton::~TNewton() {
    cout << "Zniszczono obiekt klasy TNewton\n";
}

