//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TPower.h
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#if !defined(_TPOWER_H)
#define _TPOWER_H


class TPower {
public:
	double power(double n, int m);
};

#endif  //_TPOWER_H
