//
//
//  Generated by StarUML(tm) C++ Add-In
//
//  @ Project : Untitled
//  @ File Name : TPower.cpp
//  @ Date : 16.06.2026
//  @ Author : 
//
//


#include "TPower.h"

double TPower::power(double n, int m) {
    if (m == 0) return 1;
    return n * power(n, m - 1);
}

